package com.bootshop.site.entities;
// Generated Mar 5, 2021 10:34:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="order_details")
public class OrderDetails  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

     private int id;
     private Order order;
     private ProductsSizes productsSizes;
     private int quantity;
     private float price;

    public OrderDetails() {
    }

    public OrderDetails(int id, Order order, ProductsSizes productsSizes, int quantity, float price) {
       this.id = id;
       this.order = order;
       this.productsSizes = productsSizes;
       this.quantity = quantity;
       this.price = price;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_sizes_id", nullable=false)
    public ProductsSizes getProductsSizes() {
        return this.productsSizes;
    }
    
    public void setProductsSizes(ProductsSizes productsSizes) {
        this.productsSizes = productsSizes;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=24, scale=0)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }




}


