package com.bootshop.site.entities;
// Generated Mar 5, 2021 10:34:32 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductsSizes generated by hbm2java
 */
@Entity
@Table(name = "products_sizes")
public class ProductsSizes implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private Product product;
	private Size size;
	private int quantity;
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public ProductsSizes() {
	}

	public ProductsSizes(int id, Product product, Size size, int quantity) {
		this.id = id;
		this.product = product;
		this.size = size;
		this.quantity = quantity;
	}

	public ProductsSizes(int id, Product product, Size size, int quantity, Set<OrderDetails> orderDetailses) {
		this.id = id;
		this.product = product;
		this.size = size;
		this.quantity = quantity;
		this.orderDetailses = orderDetailses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "size_id", nullable = false)
	public Size getSize() {
		return this.size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(mappedBy = "productsSizes")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

	@Override
	public String toString() {
		return "ProductsSizes [size=" + size + "]";
	}

	


}
