package com.bootshop.site.entities;
// Generated Mar 5, 2021 10:34:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="`user`")
public class User  implements java.io.Serializable {
	private static final long serialVersionUID = 1L;


     private int id;
     private String email;
     private String password;
     private String firstName;
     private String lastName;
     private String photo;
     private boolean enabled;
     private Set<OrderAddress> orderAddresses = new HashSet<OrderAddress>(0);
     private Set<Role> roles = new HashSet<Role>(0);

    public User() {
    }

	
    public User(int id, String email, String password, String firstName, String lastName, boolean enabled) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.enabled = enabled;
    }
    public User(int id, String email, String password, String firstName, String lastName, String photo, boolean enabled, Set<OrderAddress> orderAddresses, Set<Role> roles) {
       this.id = id;
       this.email = email;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.photo = photo;
       this.enabled = enabled;
       this.orderAddresses = orderAddresses;
       this.roles = roles;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="first_name", nullable=false)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="photo")
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="enabled", nullable=false)
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<OrderAddress> getOrderAddresses() {
        return this.orderAddresses;
    }
    
    public void setOrderAddresses(Set<OrderAddress> orderAddresses) {
        this.orderAddresses = orderAddresses;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="users_roles", joinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="role_id", nullable=false, updatable=false) })
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


